name: EstimAI_Immo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : récupération du dépôt applicatif
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: chaimackjs/EstimAI_Immo
          ref: main

      # Étape 2 : choix de la version Python
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      # Étape 3 : installation des dépendances
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Étape 4 : récupération des données DVF et DPE
      - name: Récupérer les données
        run: |
          python acquisition_donnees.py

      # Étape 5 : préparation des données
      - name: Préparer les données
        run: |
          python preparer_donnees.py

      # Étape 6 : entraînement des modèles
      - name: Entraîner les modèles
        run: |
          python ml.py